package com.sol.app.ui.auth

/** Un pays avec son code ISO (pour le drapeau) et son indicatif telephonique. */
data class Pays(val iso: String, val indicatif: String, val nom: String)

/** Convertit un code ISO ("HT") en drapeau emoji. */
fun drapeauEmoji(iso: String): String =
    iso.uppercase().map { c ->
        String(Character.toChars(0x1F1E6 - 'A'.code + c.code))
    }.joinToString("")

/** Liste des pays, Haiti en tete puis ordre alphabetique. */
val LISTE_PAYS = listOf(
    Pays("HT", "+509", "Haïti"),
    Pays("AF", "+93", "Afghanistan"),
    Pays("ZA", "+27", "Afrique du Sud"),
    Pays("AL", "+355", "Albanie"),
    Pays("DZ", "+213", "Algérie"),
    Pays("DE", "+49", "Allemagne"),
    Pays("AD", "+376", "Andorre"),
    Pays("AO", "+244", "Angola"),
    Pays("SA", "+966", "Arabie saoudite"),
    Pays("AR", "+54", "Argentine"),
    Pays("AM", "+374", "Arménie"),
    Pays("AU", "+61", "Australie"),
    Pays("AT", "+43", "Autriche"),
    Pays("AZ", "+994", "Azerbaïdjan"),
    Pays("BS", "+1242", "Bahamas"),
    Pays("BH", "+973", "Bahreïn"),
    Pays("BD", "+880", "Bangladesh"),
    Pays("BB", "+1246", "Barbade"),
    Pays("BE", "+32", "Belgique"),
    Pays("BZ", "+501", "Belize"),
    Pays("BJ", "+229", "Bénin"),
    Pays("BT", "+975", "Bhoutan"),
    Pays("BY", "+375", "Biélorussie"),
    Pays("MM", "+95", "Birmanie"),
    Pays("BO", "+591", "Bolivie"),
    Pays("BA", "+387", "Bosnie-Herzégovine"),
    Pays("BW", "+267", "Botswana"),
    Pays("BR", "+55", "Brésil"),
    Pays("BN", "+673", "Brunei"),
    Pays("BG", "+359", "Bulgarie"),
    Pays("BF", "+226", "Burkina Faso"),
    Pays("BI", "+257", "Burundi"),
    Pays("KH", "+855", "Cambodge"),
    Pays("CM", "+237", "Cameroun"),
    Pays("CA", "+1", "Canada"),
    Pays("CV", "+238", "Cap-Vert"),
    Pays("CF", "+236", "Centrafrique"),
    Pays("CL", "+56", "Chili"),
    Pays("CN", "+86", "Chine"),
    Pays("CY", "+357", "Chypre"),
    Pays("CO", "+57", "Colombie"),
    Pays("KM", "+269", "Comores"),
    Pays("CG", "+242", "Congo"),
    Pays("CD", "+243", "Congo (RDC)"),
    Pays("KR", "+82", "Corée du Sud"),
    Pays("KP", "+850", "Corée du Nord"),
    Pays("CR", "+506", "Costa Rica"),
    Pays("CI", "+225", "Côte d'Ivoire"),
    Pays("HR", "+385", "Croatie"),
    Pays("CU", "+53", "Cuba"),
    Pays("DK", "+45", "Danemark"),
    Pays("DJ", "+253", "Djibouti"),
    Pays("DM", "+1767", "Dominique"),
    Pays("EG", "+20", "Égypte"),
    Pays("AE", "+971", "Émirats arabes unis"),
    Pays("EC", "+593", "Équateur"),
    Pays("ER", "+291", "Érythrée"),
    Pays("ES", "+34", "Espagne"),
    Pays("EE", "+372", "Estonie"),
    Pays("SZ", "+268", "Eswatini"),
    Pays("US", "+1", "États-Unis"),
    Pays("ET", "+251", "Éthiopie"),
    Pays("FJ", "+679", "Fidji"),
    Pays("FI", "+358", "Finlande"),
    Pays("FR", "+33", "France"),
    Pays("GA", "+241", "Gabon"),
    Pays("GM", "+220", "Gambie"),
    Pays("GE", "+995", "Géorgie"),
    Pays("GH", "+233", "Ghana"),
    Pays("GR", "+30", "Grèce"),
    Pays("GD", "+1473", "Grenade"),
    Pays("GT", "+502", "Guatemala"),
    Pays("GN", "+224", "Guinée"),
    Pays("GQ", "+240", "Guinée équatoriale"),
    Pays("GW", "+245", "Guinée-Bissau"),
    Pays("GY", "+592", "Guyana"),
    Pays("HN", "+504", "Honduras"),
    Pays("HU", "+36", "Hongrie"),
    Pays("IN", "+91", "Inde"),
    Pays("ID", "+62", "Indonésie"),
    Pays("IQ", "+964", "Irak"),
    Pays("IR", "+98", "Iran"),
    Pays("IE", "+353", "Irlande"),
    Pays("IS", "+354", "Islande"),
    Pays("IL", "+972", "Israël"),
    Pays("IT", "+39", "Italie"),
    Pays("JM", "+1876", "Jamaïque"),
    Pays("JP", "+81", "Japon"),
    Pays("JO", "+962", "Jordanie"),
    Pays("KZ", "+7", "Kazakhstan"),
    Pays("KE", "+254", "Kenya"),
    Pays("KG", "+996", "Kirghizistan"),
    Pays("KI", "+686", "Kiribati"),
    Pays("KW", "+965", "Koweït"),
    Pays("LA", "+856", "Laos"),
    Pays("LS", "+266", "Lesotho"),
    Pays("LV", "+371", "Lettonie"),
    Pays("LB", "+961", "Liban"),
    Pays("LR", "+231", "Liberia"),
    Pays("LY", "+218", "Libye"),
    Pays("LI", "+423", "Liechtenstein"),
    Pays("LT", "+370", "Lituanie"),
    Pays("LU", "+352", "Luxembourg"),
    Pays("MK", "+389", "Macédoine du Nord"),
    Pays("MG", "+261", "Madagascar"),
    Pays("MY", "+60", "Malaisie"),
    Pays("MW", "+265", "Malawi"),
    Pays("MV", "+960", "Maldives"),
    Pays("ML", "+223", "Mali"),
    Pays("MT", "+356", "Malte"),
    Pays("MA", "+212", "Maroc"),
    Pays("MH", "+692", "Îles Marshall"),
    Pays("MU", "+230", "Maurice"),
    Pays("MR", "+222", "Mauritanie"),
    Pays("MX", "+52", "Mexique"),
    Pays("FM", "+691", "Micronésie"),
    Pays("MD", "+373", "Moldavie"),
    Pays("MC", "+377", "Monaco"),
    Pays("MN", "+976", "Mongolie"),
    Pays("ME", "+382", "Monténégro"),
    Pays("MZ", "+258", "Mozambique"),
    Pays("NA", "+264", "Namibie"),
    Pays("NR", "+674", "Nauru"),
    Pays("NP", "+977", "Népal"),
    Pays("NI", "+505", "Nicaragua"),
    Pays("NE", "+227", "Niger"),
    Pays("NG", "+234", "Nigeria"),
    Pays("NO", "+47", "Norvège"),
    Pays("NZ", "+64", "Nouvelle-Zélande"),
    Pays("OM", "+968", "Oman"),
    Pays("UG", "+256", "Ouganda"),
    Pays("UZ", "+998", "Ouzbékistan"),
    Pays("PK", "+92", "Pakistan"),
    Pays("PW", "+680", "Palaos"),
    Pays("PA", "+507", "Panama"),
    Pays("PG", "+675", "Papouasie-Nouvelle-Guinée"),
    Pays("PY", "+595", "Paraguay"),
    Pays("NL", "+31", "Pays-Bas"),
    Pays("PE", "+51", "Pérou"),
    Pays("PH", "+63", "Philippines"),
    Pays("PL", "+48", "Pologne"),
    Pays("PT", "+351", "Portugal"),
    Pays("QA", "+974", "Qatar"),
    Pays("DO", "+1809", "République dominicaine"),
    Pays("CZ", "+420", "République tchèque"),
    Pays("RO", "+40", "Roumanie"),
    Pays("GB", "+44", "Royaume-Uni"),
    Pays("RU", "+7", "Russie"),
    Pays("RW", "+250", "Rwanda"),
    Pays("KN", "+1869", "Saint-Kitts-et-Nevis"),
    Pays("LC", "+1758", "Sainte-Lucie"),
    Pays("VC", "+1784", "Saint-Vincent-et-les-Grenadines"),
    Pays("SM", "+378", "Saint-Marin"),
    Pays("SB", "+677", "Îles Salomon"),
    Pays("SV", "+503", "Salvador"),
    Pays("WS", "+685", "Samoa"),
    Pays("ST", "+239", "Sao Tomé-et-Principe"),
    Pays("SN", "+221", "Sénégal"),
    Pays("RS", "+381", "Serbie"),
    Pays("SC", "+248", "Seychelles"),
    Pays("SL", "+232", "Sierra Leone"),
    Pays("SG", "+65", "Singapour"),
    Pays("SK", "+421", "Slovaquie"),
    Pays("SI", "+386", "Slovénie"),
    Pays("SO", "+252", "Somalie"),
    Pays("SD", "+249", "Soudan"),
    Pays("SS", "+211", "Soudan du Sud"),
    Pays("LK", "+94", "Sri Lanka"),
    Pays("SE", "+46", "Suède"),
    Pays("CH", "+41", "Suisse"),
    Pays("SR", "+597", "Suriname"),
    Pays("SY", "+963", "Syrie"),
    Pays("TJ", "+992", "Tadjikistan"),
    Pays("TZ", "+255", "Tanzanie"),
    Pays("TD", "+235", "Tchad"),
    Pays("TH", "+66", "Thaïlande"),
    Pays("TL", "+670", "Timor oriental"),
    Pays("TG", "+228", "Togo"),
    Pays("TO", "+676", "Tonga"),
    Pays("TT", "+1868", "Trinité-et-Tobago"),
    Pays("TN", "+216", "Tunisie"),
    Pays("TM", "+993", "Turkménistan"),
    Pays("TR", "+90", "Turquie"),
    Pays("TV", "+688", "Tuvalu"),
    Pays("UA", "+380", "Ukraine"),
    Pays("UY", "+598", "Uruguay"),
    Pays("VU", "+678", "Vanuatu"),
    Pays("VE", "+58", "Venezuela"),
    Pays("VN", "+84", "Vietnam"),
    Pays("YE", "+967", "Yémen"),
    Pays("ZM", "+260", "Zambie"),
    Pays("ZW", "+263", "Zimbabwe"),
)
